# syntax=docker/dockerfile:1

FROM golang:1.25-alpine AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o /app/account_service ./cmd/account_service

FROM alpine:3.18
RUN apk add --no-cache ca-certificates
WORKDIR /app

COPY --from=builder /app/account_service ./account_service
COPY pkgs/config/config.yaml ./config.yaml

EXPOSE 8080 50051
ENV CONFIG_PATH=/app/config.yaml

CMD ["/app/account_service"]
